# Generated by Django 6.0.3 on 2026-04-28 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("interactions", "0002_watchlist_movie_alter_watchlist_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="watched",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="movie",
            field=models.ForeignKey(
                default=132,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_watchlist",
                to="catalog.movie",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
