# Generated by Django 6.0.3 on 2026-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('subscriptions', '0002_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available_in_plans',
            field=models.ManyToManyField(blank=True, related_name='movies', to='subscriptions.subscriptionplan', verbose_name='Доступ в планах'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
