# Generated by Django 6.0.3 on 2026-05-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_free',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
