# Generated by Django 6.0.3 on 2026-05-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movie_available_in_plans_movie_is_free'),
        ('catalog', '0002_movie_is_free'),
    ]

    operations = [
    ]
